android.bundle.enableUncompressedNativeLibs=false
RELEASE_STORE_FILE=C\:\\androidkeystore\\keystore.jks
RELEASE_STORE_PASSWORD=Crocodilush2026!
RELEASE_KEY_ALIAS=upload
RELEASE_KEY_PASSWORD=Crocodilush2026!
